version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-manager
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - database
        volumes:
            - ./:/var/www
        networks:
            - project

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        container_name: app-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - project
        depends_on:
            - app

    database:
        build: ./docker/mysql
        container_name: mysql
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'app'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/.dbdata:/var/lib/mysql
        networks:
            - project
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - project

networks:
    project:
        driver: bridge
